name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Grant execute permissions to Gradle wrapper
      run: chmod +x ./gradlew
        
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Tests
      run: ./gradlew test
      
